# 01-data-types 文件列表
# Generated by generate_chapter.sh

+incdir+.
+incdir+../common/utils

# DUT
dut/simple_alu.sv

# Examples
examples/01_basic_types.sv
examples/02_arrays.sv
examples/03_struct_enum.sv
examples/04_type_casting.sv

# Testbench
tb/tb_data_types.sv
